resolver: lts-18.21

packages:
  - euterpea
  - avril14

extra-deps:
  - Cabal-3.0.1.0
  - PortMidi-0.2.0.0
  - bytestring-0.10.8.2
  - binary-0.8.9.0
  - directory-1.3.7.0
  - parsec-3.1.15.0
  - process-1.6.13.2
  - text-1.2.5.0
  - unix-2.7.2.2
